### ISSUE TITLE
How to create empty folder?

### ISSUE THREAD

**Issue by kidok313** [Huuums/vscode-fast-folder-structure#11]
I need to add some empty folders to my structure. What command allows me to create one?

**Comment by Huuums** [comment]
Thanks for reaching out!

This was not possible until now. 

A new version will be published in a bit which will give you the ability to simply pass `EmptyDirectory` as a value for `template`. This will then create a directory for you.

```
 "structure": [
                {
                  "fileName": "No files in here",
                  "template": "EmptyDirectory"
                }]
```
