### ISSUE TITLE
Cannot add multiple empty directories

### ISSUE THREAD

**Issue by ResoDev** [Huuums/vscode-fast-folder-structure#13]
Hello, thanks for the awesome extension!

When you specify `EmptyDirectory` twice such as in the following snippet:
```json
{
  "fileName": "domain/objects",
  "template": "EmptyDirectory"
},
{
  "fileName": "ui/pages/<FFSName>_page.dart",
},
{
  "fileName": "ui/widgets",
  "template": "EmptyDirectory"
},
```

Only the first empty directory gets created.

**Comment by Huuums** [comment]
Thank you for using the extension and contributing! I will publish a new version to fix this shortly.
