### ISSUE TITLE
Feature Request: Custom transformer

### ISSUE THREAD

**Issue by ChristopherBass** [Huuums/vscode-fast-folder-structure#143]
Is it possible to create a custom Transformer?

My original desire was to inject a Guid as I'm generating the output, but I don't think that's an option.

If I could just code my own transformer in ts, I could use the transformer to just output a random Guid, or one based on the input.

**Comment by Huuums** [comment]
Hi @ChristopherBass ,

it is not possible to create your own custom transformer. I will also not implement this functionality as this will result in the extension having to evaluate code from the users in their template. I would like to not open this box of pandora.  

I'm currently working on expanding functionality of the extension in a few ways and while i'm at it I can also add a way of generating random IDs.

Unfortunately all of this will take a while until it's finished. Sorry I can't provide a better solution faster
