### ISSUE TITLE
Classname transformation

### ISSUE THREAD

**Issue by Brydom** [Huuums/vscode-fast-folder-structure#19]
- `classname`
  - `lol-sick-component` -> `LolSickComponent`
  - `lol sick component` -> `LolSickComponent`
  - `lol_sick-component.dude` -> `LolSickComponentDude`

Ultimately, I think you could find any non-A-Z character and replace it with nothing, and adjust the 
character after it to be a capital.

```js
const stringToClassName = string => {
  string = string.toLowerCase().replace(/[^A-Za-z0-9]/g, ' ').split(" ");
  string = string.map(word => word[0].toUpperCase() + word.substr(1, word.length));
  return string.join("");
}

const shortStringToClassName = string => string
  .toLowerCase()
  .replace(/[^A-Za-z0-9]/g, ' ')
  .split(" ")
  .map(word => word[0].toUpperCase() + word.substr(1, word.length))
  .join("");

console.log(stringToClassName('some-Test.dude'));
// SomeTestDude
console.log(shortStringToClassName('HEY/this|NEAT'));
// HeyThisNeat
```

This would solve having a component name: `button-group`, and with the `uppercase` transformation: `Button-group`, which is invalid as JS.

**Comment by Huuums** [comment]
Thanks for the suggestion. 

The transformer for this will be `pascalcase` and while I'm at it I will also implement a `camelcase` transfomer which will not capitalize the first letter.
