### ISSUE TITLE
How to use this extension

### ISSUE THREAD

**Issue by ggMartinez** [Huuums/vscode-fast-folder-structure#26]
Sorry for the lame ticket, but I don't understand how to use this extension.

Don't now where to create templates for example, can someone give me a hand with this?

**Comment by Huuums** [comment]
Thanks for reaching out. 

You can define the templates inside the settings.json of Visual Studio Code.

**Comment by Brydom** [comment]
@Huums think it would be worth adding a small blurb in the readme about first-timers? VSCode settings are weird and it might help some people - especially with people who haven't touched that file before!
