### ISSUE TITLE
Right click for easy adding of templates

### ISSUE THREAD

**Issue by howagain** [Huuums/vscode-fast-folder-structure#27]
I feel that this extension would be better with the ability to quickly create a template based on a folder that the user right-clicks on and selects "create a new template in FFS from this folder". 

The base functionality would just be to duplicate the folder but it would also open the editor for that template and allow you to use that "copy" as a starting point for a generalized template based on that folder structure.

**Comment by Huuums** [comment]
Hey, thanks for the suggestion. I agree that this would make things easier. 

I've been thinking for a while how to make this possible but can't find a good way. I'll play around with the idea and fiddle around with it. 

Don't hold your breath for this because I don't know how long I'll need but it will come at some point :)

**Comment by Brydom** [comment]
I've thought about this as well! In React, being able to have your components as templates and so forth would be great. If you'd like some help implementing this (I have never used TS though) I'd be happy to try - or create a mockup for you!

**Comment by Huuums** [comment]
Moin moin,

I think I have a somewhat working solution and would like to ask you to give your opinion. 

Is this what you thought of and would like to have? 

[Demo GIF](https://gfycat.com/unhappygrandindianhare)

What this does right now is:

1. Ask you what your new template is supposed to be named.
2. Ask you for which files in the folder you would like to create file templates
3. Go through all the filenames and filecontent in the folder and checks for possible Custom FFS-Variables that you might want to use. (If it finds any it asks you which of them you actually want to use)
4. Writes the template into your settings.json

From what I've seen it's not possible to make this extension open up some editors to let you edit the files before saving the data into the settings. So you would have to create the template structure before doing the `right-click -> Create FFS-Template`. But I might be wrong on this.
