### ISSUE TITLE
🐛 Mixed Context!

### ISSUE THREAD

**Issue by arash-bizcover** [Huuums/vscode-fast-folder-structure#32]
There is a scope/context issue with this plugin.
It doesn't act normally on user context vs workspace context.
Meaning if I'm not opening any workspace settings should be added/modified/deleted in the user settings.

On the other hand If I'm inside a specific workspace it should ask to save/modify in global or workspace settings.

_To simplify things, it could always write to user's settings rather than workspace_

**Comment by Huuums** [comment]
I will have an update ready shortly that will write the new template into the user settings as long as there are no templates defined in the current workspace. 

However if there are templates defined in the current workspace it will automatically save the new template into workspace settings.
