### ISSUE TITLE
🐛 Deleted Templates keep coming back

### ISSUE THREAD

**Issue by arash-bizcover** [Huuums/vscode-fast-folder-structure#33]
I cannot delete the default templates:
"TS React Functional Component" 
"JS React Functional Component"
"Indexfile Import/Export"

On next template creation they will keep coming back. 😞

**Comment by Huuums** [comment]
Thanks for reaching out! 

I thought about removing the default templates out of the plugin completely anyway since there is no use for them as everyone has different needs for their own templates. 

That should also fix your issue at the same time. Update will happen anytime soon
