### ISSUE TITLE
How to use my saved folder with just one command?

### ISSUE THREAD

**Issue by njoppi2** [Huuums/vscode-fast-folder-structure#37]
Hello,  great extension! But one thing that would really make it faster for people like me that like to use keybinds, is a way of executing the command FFS.createFolderStructure just by doing a setted keybind like "ctrl+8" (in my case). When i tried to do this I created this command in my keybindings.json`{
   "key": "ctrl+8",
   "command": "FFS.createFolderStructure",
}
`, but it doesn't work the way it should :(, if do the keybind, the input to put the name of the file appears:
![Screenshot from 2020-09-26 15-50-55](https://user-images.githubusercontent.com/16853682/94348130-2f6bc200-0010-11eb-9bac-507170b0f28f.png)

but then a error occurs if I press enter: 
![Screenshot from 2020-09-26 15-51-00](https://user-images.githubusercontent.com/16853682/94348132-32ff4900-0010-11eb-92b5-b612db89f15a.png)
how can I use this? :/

**Comment by Huuums** [comment]
Hey @njoppi2, 

Thanks for reaching out. 

which version of FFS are you using? I think it should work with the command via shortcut. 

If you do not use the mouse to rightclick on a folder in the treeview and click "create folder" from there, VS Code does not give a path of the folder in which the templated folders should be created. 

So what I did is an extra prompt **before** entering the component name where you specify the path in which the new folder should be created. 

![grafik](https://user-images.githubusercontent.com/9745322/94349747-c738d280-0047-11eb-93f5-e3b9b7316410.png)
![grafik](https://user-images.githubusercontent.com/9745322/94349750-d4ee5800-0047-11eb-8b88-ff0b6ecb5da2.png)

and after you entered the path you are asked for the component name. 

Is this not happening for you?

**Comment by njoppi2** [comment]
My version is v2.0.0
I just tested now and it worked just like you said, not sure what happened before.
But I'd like to know, is it possible to make this mid-step automatic, so that we don't have to write the current folder? Maybe making it possible to pass an arg like this? `{
   "key": "ctrl+8",
   "command": "FFS.createFolderStructure",
   "arg": { "current": true }
  },
`
just a sugestion, it'd be really awesome!

**Comment by Huuums** [comment]
I will take a look when I find some time. But just to be sure: What would you expect `current` to be? The extension has no context from where you enter the command (as far as I know at least). Is `current` the file that you at that moment have open in the editor?

**Comment by njoppi2** [comment]
I was thinking about it being the current folder, not file, because as far as I know it would not work to create a folder inside the file, right? Btw, one thing that I really have no idea if it can help you are the ">copy path" commands that you can write in the ctrl+shift+p input, and they'll return to you your current path, maybe you could use something like this?

**Comment by Huuums** [comment]
I'm still not sure I understand.

Current folder would be what exactly in your case?
- Root folder of the project? (Doesn't make sense, I think )
- Current folder the active file is in? 
This might also be bad because if you have a `components/<component>/index.js` format then you would create the next component inside the components/<component> folder next to the index.js. 

I'm thinking that instead of passing an arg that is called `current` you could pass something like 
`{parentFolder: 'src/components'}` instead of having to enter it everytime. 

This has the caveat that you would have to create multiple keybinds for different folders but it's pretty much the only solution I can think of right now that would work without issues and has the highest success rate.

**Comment by njoppi2** [comment]
```
Current folder the active file is in?
This might also be bad because if you have a components/<component>/index.js format then you would create the next component inside the components/ folder next to the index.js.
```

exactly, at least for me, all the times that I create components with FFS, I want them simply to be inside the current folder that I'm in, next to my index.ts file (if it's still not clear I can send you a print when I get home)

**Comment by njoppi2** [comment]
I never create folders/files with FFS in a outside component like src/components, this could be useful for someone, but at least for me it's not something I'd do

**Comment by Huuums** [comment]
Alright, I understand your usecase now. 

I will implement this once I find time although I think that your usecase is a somewhat rare one.

**Comment by njoppi2** [comment]
omg thank you!! :D

**Comment by Huuums** [comment]
@njoppi2 you can now pass the argument "__current" and it should do as you requested. 

For more information check the readme :)
