### ISSUE TITLE
<FFSName> string Transformation

### ISSUE THREAD

**Issue by marcocavanna** [Huuums/vscode-fast-folder-structure#9]
It would be nice if <FFSName> could be transformed using some "default" filter like: `upperCase`, `lowerCase`, `title` ecc. ecc.

Template idea:
```JSON
"fastFolderStructure.fileTemplates": {
    "React Component": [
      "import React from 'react';",
      "",
      "import { } from './<FFSName>-component';",
      "import { } from './<FFSName>-function';",
      "",
      "const <FFSName | title> = () => <h1><FFSName> Page Component</h1>;",
      "",
      "export default <FFSName | title>;",
      ""
    ]
  }
```

So creating a React Component passing 'home' as FFSName it would produce all structure using `name` (lower case) except instruction with `<FFSName | title>` that will transform `home` into `Name`.

I think this could be a useful RegExp to help get the FFSName and the relative Filter
```js
const regexp = /<FFSName(?:\s*\|\s*([A-Za-z]+))?>/;
```

**Comment by Huuums** [comment]
Thanks for the suggestion, seems like a useful addition.  

I will take a look at this.
